spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: path-route-base
          uri: http://localhost:8000/persons
          predicates:
            - Path=/persons/**
          filters:
            - AddResponseHeader=X-Gateway, cloud-gateway
            - name: CircuitBreaker
              args:
                name: PersonService
                fallbackUri: forward:/fallback
            - name: Retry
              args:
                retries: 3
                method: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
        - id: person-fallback
          uri: http://localhost:8001
          predicates:
            - Path=/fallback
          filters:
            - name: FallbackHeaders
              args:
                executionExceptionTypeHeaderName: X-Fallback



logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

