spring:
  cloud:
    gateway:
      routes:
        - id: path-route-base
          uri: https://example.org
          predicates:
            - name: Path
              args:
                - /api/{segment}
          filters:
            - AddResponseHeader=X-Gateway, spring-gateway-{segment}
