spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: path-route-base
          uri: http://localhost:8000/persons
          predicates:
            - Path=/persons/**
          filters:
            - AddResponseHeader=X-Gateway, cloud-gateway
