server:
  port: 8002

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/auth/realms/PolarBookshop
  data:
    mongodb:
      host: localhost
      port: 27017
      username: spring-cloud
      password: spring-cloud
      database: spring-cloud


